name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/ellipse_5.png
  - assets/vectors/vector_188_x2.svg
  - assets/vectors/ellipse_56_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/images/ellipse_5.png
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/vector_152_x2.svg
  - assets/vectors/vector_125_x2.svg
  - assets/vectors/ellipse_51_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_200_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/images/ellipse_645.jpeg
  - assets/vectors/vector_181_x2.svg
  - assets/vectors/vector_207_x2.svg
  - assets/vectors/ellipse_6423_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_158_stroke_26_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_111_x2.svg
  - assets/images/djvstock_create_aphoto_of_ayoung_man_with_aclean_look_1.png
  - assets/vectors/vector_202_x2.svg
  - assets/vectors/group_131_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_116_x2.svg
  - assets/vectors/vector_183_x2.svg
  - assets/images/gold_white_beauty_logo_41.png
  - assets/vectors/devicongoogle_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/images/woman_45146101.png
  - assets/images/recruitment_27669061.png
  - assets/images/rectangle_47.jpeg
  - assets/images/djvstock_create_aphoto_of_ayoung_man_with_aclean_look_1.png
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/container_2_x2.svg
  - assets/vectors/vector_171_x2.svg
  - assets/vectors/vector_107_x2.svg
  - assets/vectors/vector_175_x2.svg
  - assets/vectors/group_172_x2.svg
  - assets/vectors/vector_184_x2.svg
  - assets/vectors/group_108_x2.svg
  - assets/vectors/vector_198_x2.svg
  - assets/vectors/group_127_x2.svg
  - assets/vectors/vector_165_x2.svg
  - assets/vectors/ellipse_631_x2.svg
  - assets/vectors/vector_160_x2.svg
  - assets/images/ellipse_646.jpeg
  - assets/vectors/vector_193_x2.svg
  - assets/vectors/vector_158_stroke_43_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/ellipse_6428_x2.svg
  - assets/images/ellipse_643.jpeg
  - assets/vectors/vector_158_stroke_30_x2.svg
  - assets/vectors/ellipse_6441_x2.svg
  - assets/images/ellipse_6411.jpeg
  - assets/vectors/ellipse_6438_x2.svg
  - assets/vectors/vector_158_stroke_15_x2.svg
  - assets/images/ellipse_645.jpeg
  - assets/vectors/vector_158_stroke_32_x2.svg
  - assets/vectors/ellipse_6439_x2.svg
  - assets/images/ellipse_644.jpeg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/vector_158_stroke_27_x2.svg
  - assets/vectors/ellipse_6436_x2.svg
  - assets/vectors/vector_180_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/vector_146_x2.svg
  - assets/vectors/vector_140_x2.svg
  - assets/images/ellipse_643.jpeg
  - assets/vectors/ellipse_6417_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/vector_158_stroke_13_x2.svg
  - assets/vectors/vector_121_x2.svg
  - assets/vectors/vector_176_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_168_x2.svg
  - assets/images/ellipse_644.jpeg
  - assets/images/ellipse_648.png
  - assets/vectors/vector_158_stroke_20_x2.svg
  - assets/vectors/ellipse_6437_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/group_1271_x2.svg
  - assets/vectors/ellipse_6431_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_158_stroke_39_x2.svg
  - assets/vectors/container_6_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/vector_158_stroke_29_x2.svg
  - assets/vectors/vector_80_x2.svg
  - assets/vectors/ellipse_65_x2.svg
  - assets/images/ellipse_642.png
  - assets/images/ellipse_648.png
  - assets/vectors/ellipse_653_x2.svg
  - assets/vectors/ellipse_6446_x2.svg
  - assets/vectors/vector_158_stroke_36_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/images/ellipse_6410.jpeg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/vector_124_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_158_stroke_44_x2.svg
  - assets/vectors/vector_104_x2.svg
  - assets/vectors/vector_144_x2.svg
  - assets/vectors/ellipse_6427_x2.svg
  - assets/images/ellipse_647.png
  - assets/vectors/vector_147_x2.svg
  - assets/vectors/vector_162_x2.svg
  - assets/vectors/ellipse_6425_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/vector_158_stroke_17_x2.svg
  - assets/images/ellipse_649.jpeg
  - assets/vectors/ellipse_6448_x2.svg
  - assets/vectors/vector_158_stroke_24_x2.svg
  - assets/vectors/vector_158_stroke_7_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/vector_155_x2.svg
  - assets/vectors/vector_204_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_156_x2.svg
  - assets/vectors/container_8_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/vectors/vector_148_x2.svg
  - assets/vectors/vector_119_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_135_x2.svg
  - assets/vectors/vector_130_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/vector_128_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/images/ellipse_6411.jpeg
  - assets/vectors/ellipse_6432_x2.svg
  - assets/vectors/vector_158_stroke_37_x2.svg
  - assets/images/ellipse_5.png
  - assets/vectors/ellipse_53_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/vector_106_x2.svg
  - assets/vectors/vector_170_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_134_x2.svg
  - assets/vectors/vector_177_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/images/djvstock_create_aphoto_of_ayoung_man_with_aclean_look_1.png
  - assets/vectors/vector_185_x2.svg
  - assets/vectors/vector_163_x2.svg
  - assets/vectors/vector_201_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_110_x2.svg
  - assets/vectors/vector_158_stroke_6_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/group_13_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_142_x2.svg
  - assets/vectors/vector_114_x2.svg
  - assets/vectors/vector_118_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/vector_103_x2.svg
  - assets/vectors/vector_149_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/images/ellipse_642.png
  - assets/vectors/ellipse_6434_x2.svg
  - assets/vectors/vector_158_stroke_16_x2.svg
  - assets/images/ellipse_5.png
  - assets/vectors/vector_84_x2.svg
  - assets/vectors/vector_132_x2.svg
  - assets/vectors/ellipse_52_x2.svg
  - assets/vectors/vector_190_x2.svg
  - assets/images/ellipse_5.png
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/ellipse_55_x2.svg
  - assets/vectors/vector_127_x2.svg
  - assets/vectors/vector_174_x2.svg
  - assets/images/ellipse_643.jpeg
  - assets/images/ellipse_649.jpeg
  - assets/images/ellipse_648.png
  - assets/images/ellipse_644.jpeg
  - assets/vectors/vector_158_stroke_1_x2.svg
  - assets/vectors/vector_158_stroke_33_x2.svg
  - assets/vectors/container_3_x2.svg
  - assets/vectors/vector_206_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/ellipse_6442_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/ellipse_651_x2.svg
  - assets/vectors/vector_158_stroke_x2.svg
  - assets/vectors/vector_158_stroke_31_x2.svg
  - assets/vectors/ellipse_6415_x2.svg
  - assets/vectors/container_5_x2.svg
  - assets/vectors/vector_158_stroke_35_x2.svg
  - assets/vectors/ellipse_6443_x2.svg
  - assets/vectors/ellipse_6440_x2.svg
  - assets/vectors/group_1274_x2.svg
  - assets/images/ellipse_648.png
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/vector_158_stroke_2_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_151_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/vectors/ellipse_6422_x2.svg
  - assets/images/ellipse_649.jpeg
  - assets/vectors/vector_129_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_158_stroke_22_x2.svg
  - assets/vectors/ellipse_6433_x2.svg
  - assets/vectors/vector_203_x2.svg
  - assets/vectors/vector_91_x2.svg
  - assets/images/ellipse_642.png
  - assets/vectors/vector_108_x2.svg
  - assets/vectors/vector_96_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/ellipse_6429_x2.svg
  - assets/vectors/vector_158_stroke_23_x2.svg
  - assets/vectors/vector_141_x2.svg
  - assets/vectors/vector_158_stroke_11_x2.svg
  - assets/vectors/vector_120_x2.svg
  - assets/vectors/vector_126_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/images/plus_96419021.png
  - assets/images/djvstock_create_aphoto_of_ayoung_man_with_aclean_look_1.png
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_179_x2.svg
  - assets/vectors/vector_158_x2.svg
  - assets/vectors/vector_161_x2.svg
  - assets/images/rectangle_49.jpeg
  - assets/vectors/vector_102_x2.svg
  - assets/vectors/vector_169_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/vector_199_x2.svg
  - assets/vectors/vector_153_x2.svg
  - assets/vectors/solargallery_bold_x2.svg
  - assets/vectors/ictwotone_photo_camera_front_x2.svg
  - assets/images/djvstock_create_aphoto_of_ayoung_man_with_aclean_look_1.png
  - assets/vectors/vector_150_x2.svg
  - assets/vectors/vector_99_x2.svg
  - assets/vectors/vector_192_x2.svg
  - assets/vectors/vector_123_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/group_132_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_98_x2.svg
  - assets/vectors/vector_187_x2.svg
  - assets/vectors/vector_167_x2.svg
  - assets/vectors/vector_158_stroke_18_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_105_x2.svg
  - assets/vectors/vector_109_x2.svg
  - assets/vectors/vector_197_x2.svg
  - assets/images/ellipse_649.jpeg
  - assets/images/ellipse_648.png
  - assets/images/ellipse_64.png
  - assets/images/ellipse_6410.jpeg
  - assets/images/ellipse_643.jpeg
  - assets/vectors/vector_157_x2.svg
  - assets/vectors/vector_196_x2.svg
  - assets/vectors/ellipse_6413_x2.svg
  - assets/vectors/container_4_x2.svg
  - assets/vectors/vector_158_stroke_41_x2.svg
  - assets/vectors/group_1272_x2.svg
  - assets/vectors/container_7_x2.svg
  - assets/vectors/ellipse_6418_x2.svg
  - assets/vectors/vector_158_stroke_38_x2.svg
  - assets/vectors/vector_158_stroke_5_x2.svg
  - assets/vectors/vector_154_x2.svg
  - assets/vectors/ellipse_6412_x2.svg
  - assets/vectors/vector_158_stroke_14_x2.svg
  - assets/vectors/ellipse_6445_x2.svg
  - assets/vectors/vector_158_stroke_12_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/ellipse_652_x2.svg
  - assets/images/ellipse_64.png
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_137_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_159_x2.svg
  - assets/vectors/vector_158_stroke_4_x2.svg
  - assets/vectors/ellipse_6447_x2.svg
  - assets/images/ellipse_5.png
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_164_x2.svg
  - assets/vectors/ellipse_6_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/vector_1651_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/ellipse_63_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_191_x2.svg
  - assets/vectors/group_140_x2.svg
  - assets/vectors/vector_178_x2.svg
  - assets/vectors/group_1273_x2.svg
  - assets/images/ellipse_6411.jpeg
  - assets/vectors/vector_158_stroke_19_x2.svg
  - assets/vectors/vector_83_x2.svg
  - assets/vectors/vector_136_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/ellipse_6444_x2.svg
  - assets/vectors/vector_115_x2.svg
  - assets/vectors/vector_195_x2.svg
  - assets/images/ellipse_641.jpeg
  - assets/vectors/vector_133_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_158_stroke_40_x2.svg
  - assets/vectors/vector_194_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/vector_122_x2.svg
  - assets/vectors/ellipse_6421_x2.svg
  - assets/images/ellipse_6410.jpeg
  - assets/vectors/vector_158_stroke_10_x2.svg
  - assets/vectors/ellipse_6416_x2.svg
  - assets/images/ellipse_5.png
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/vector_165_x2.svg
  - assets/vectors/ellipse_54_x2.svg
  - assets/vectors/vector_172_x2.svg
  - assets/vectors/vector_131_x2.svg
  - assets/vectors/vector_189_x2.svg
  - assets/vectors/vector_182_x2.svg
  - assets/vectors/vector_166_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/vector_138_x2.svg
  - assets/vectors/vector_139_x2.svg
  - assets/vectors/vector_112_x2.svg
  - assets/images/ellipse_646.jpeg
  - assets/images/ellipse_645.jpeg
  - assets/images/ellipse_647.png
  - assets/vectors/vector_158_stroke_25_x2.svg
  - assets/vectors/ellipse_6430_x2.svg
  - assets/vectors/vector_158_stroke_28_x2.svg
  - assets/vectors/ellipse_6419_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_158_stroke_3_x2.svg
  - assets/vectors/ellipse_6449_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/vectors/vector_117_x2.svg
  - assets/images/ellipse_6410.jpeg
  - assets/images/ellipse_64.png
  - assets/images/ellipse_6411.jpeg
  - assets/images/ellipse_641.jpeg
  - assets/images/ellipse_642.png
  - assets/vectors/vector_158_stroke_42_x2.svg
  - assets/vectors/ellipse_6424_x2.svg
  - assets/vectors/vector_143_x2.svg
  - assets/vectors/vector_158_stroke_21_x2.svg
  - assets/vectors/vector_158_stroke_9_x2.svg
  - assets/vectors/ellipse_6435_x2.svg
  - assets/vectors/ellipse_6426_x2.svg
  - assets/vectors/vector_145_x2.svg
  - assets/vectors/ellipse_6420_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/vector_158_stroke_8_x2.svg
  - assets/vectors/vector_158_stroke_34_x2.svg
  - assets/vectors/ellipse_6414_x2.svg
  - assets/vectors/vector_186_x2.svg
  - assets/vectors/vector_173_x2.svg
  - assets/vectors/vector_113_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/images/skinza_logo.png
  - assets/vectors/vector_165_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/vector_172_x2.svg



